"""add detection table

Revision ID: 2965f32500cf
Revises: fe56fa70289e
Create Date: 2026-10-07 17:48:07.794353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2965f32500cf'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_w', sa.Float(), nullable=False),
    sa.Column('bbox_h', sa.Float(), nullable=False),
    sa.Column('defect_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('track_segment', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('milepost', sa.Float(), nullable=True),
    sa.Column('captured_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='detectionstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_captured_at'), 'detection', ['captured_at'], unique=False)
    op.create_index(op.f('ix_detection_confidence'), 'detection', ['confidence'], unique=False)
    op.create_index(op.f('ix_detection_defect_type'), 'detection', ['defect_type'], unique=False)
    op.create_index(op.f('ix_detection_status'), 'detection', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_status'), table_name='detection')
    op.drop_index(op.f('ix_detection_defect_type'), table_name='detection')
    op.drop_index(op.f('ix_detection_confidence'), table_name='detection')
    op.drop_index(op.f('ix_detection_captured_at'), table_name='detection')
    op.drop_table('detection')
    # ### end Alembic commands ###
